Repository puppetlabs/puppet-commit, pull requests merged in 2023-07, with the labels that each got.

#1 Inital commit to create the base ruby gem
  .gitignore
  Gemfile
  LICENSE
  Rakefile
  lib/puppet-commit/version.rb
  puppet-commit.gemspec
Labels: maintenance

#2 add gem and script file
  Gemfile
  exe/commits.rb
  puppet-commit.gemspec
Labels: enhancement

#3 add gem and script file
  bin/puppet-commit
  puppet-commit.gemspec
Labels: maintenance

#4 Create script
  README.md
Labels: maintenance

#5 Executable in bin/ now consumes lib/ code
  bin/puppet-commit
  lib/puppet-commit.rb
Labels: enhancement

#7 (maint) - add the ai api call
  lib/puppet-commit.rb
Labels: maintenance

#10 fix: Update documentation for git commit message length limit
  lib/puppet-commit.rb
Labels: maintenance

#11 (maint) - rubocop fixes
  Gemfile
  README.md
  lib/puppet-commit.rb
  puppet-commit.gemspec
Labels: maintenance

#12 fix: Update commit message in PuppetCommit class
  lib/puppet-commit.rb
Labels: maintenance

#15 Add commit message prompt and staging files
  lib/puppet-commit.rb
Labels: enhancement

#16 Update license in puppet-commit.gemspec to Apache-2.0
  LICENSE
  puppet-commit.gemspec
Labels: maintenance

#17 feat: Add ruby_figlet gem for AI commit art
  Gemfile
  lib/puppet-commit.rb
Labels: enhancement

#18 feat: Update commit message formatting and function names
  lib/puppet-commit.rb
Labels: maintenance

#19 Maint: Update commit message generation and user prompt
  lib/puppet-commit.rb
Labels: maintenance

#20 Add 3 retry attempts
  lib/puppet-commit.rb
Labels: enhancement

#25 style: Documentation only changes
  lib/puppet-commit.rb
Labels: maintenance

#22 (feat) Add functionality to retrieve current branch name
  lib/puppet-commit.rb
Labels: enhancement

#31 Update Gemfile and puppet-commit script
  Gemfile
  bin/puppet-commit
  lib/puppet-commit.rb
Labels: maintenance

#30 Add demo video to README.md
  README.md
Labels: maintenance

#35 Add --create-pr instructions and demo to README
  README.md
Labels: maintenance

#37 Update gem dependencies and required Ruby version
  Gemfile
  lib/puppet-commit.rb
  puppet-commit.gemspec
Labels: feature
